[advisories]
vulnerability = "deny"
unmaintained = "deny"
notice = "deny"
yanked = "deny"
ignore = []

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-3-Clause",
    "BSL-1.0",
    "ISC",
    "Unicode-DFS-2016",
    "Zlib",
    "CC0-1.0",
    "Unlicense",
]
deny = []
copyleft = "warn"

[bans]
multiple-versions = "deny"
skip-tree = []

[sources]
allow-git = []
